spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/userDb
    datasource:
      driver-class-name: mongodb.jdbc.MongoDriver

app:
  exceptionMessage: User already exists!
  globalExceptionMessage: Database connectivity lost!

